[package]
name = "hex-interactive/cooldownmanager"
description = "Implements a cooldown system and a way to manage one or more of them"
version = "1.0.1"
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"
license = "MIT"
