[package]
name = "hex-interactive/ui"
description = "Handles initialization and storage of prebuilt GUIs"
version = "1.0.0"
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"
license = "MIT"
