[package]
name = "hex-interactive/rogueproperty"
description = "Represents a property with configurable and stacking modifiers"
version = "3.0.0"
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"
license = "MIT"
